# App
spring.application.name=cloud-optimizer
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/cloud_optimizer

# JWT secret (must match JwtUtil.java ? exactly this string)
jwt.secret=mysecretkeymysecretkeymysecretkey12

# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html

# Show SQL-equivalent MongoDB queries in logs (optional but useful)
logging.level.org.springframework.data.mongodb=DEBUG

server.forward-headers-strategy=framework
springdoc.swagger-ui.use-root-path=true

server.tomcat.remoteip.protocol-header=x-forwarded-proto
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs